---
title: RIOT RI
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: page
    Has Photo Banner: true
    Thumbnail Image: "/uploads/RiotRI-Picture2.jpg"
- scope:
    path: ''
    type: pages
  values:
    layout: page
    Has Photo Banner: true
    Has Visible Header: true
    Has Subpages Embedded: false
    Description: 
    Header Button:
      Text: 
      URL: 
    Thumbnail Image: 
    Slideshow Images:
    - ''
gems:
- jekyll-paginate
plugins_dir:
- jekyll-paginate
- jekyll-feed
paginate: 8
paginate_path: "/news/:num/"
description: 'RIOT Rhode Island is a volunteer-based non-profit that uses music creation
  and critical thinking to foster empowerment, collaborative relationships, and the
  development of healthy identities in girls, women, trans, and gender expansive youth
  and adults.  '
Banner Color: "#e8483c"
Announcement Banner Text: Registration for Youth Rock Camp opens Monday, February
  28 at 12:00 PM!
Background Color: "#000"
Accent Color 1: "#ffe22b"
Accent Color 2: "#00c4bb"
Accent Color 3: "#5151bf"
Menu Image: "/uploads/RIOT-menu-icon.svg"
Site Logo: "/uploads/RIOT-Logo.svg"
Site Vertical Logo: "/uploads/RIOT-Logo-Portrait.svg"
Favicon Image: "/uploads/RIOT-Favicon.png"
Default Thumbnail Image: "/uploads/RiotRI-Picture.jpg"
baseurl: 
url: http://riotri.org
Social Media:
  Instagram:
    URL: https://www.instagram.com/girlsrockri
    Icon Image: "/uploads/instagram-icon.svg"
  Facebook:
    URL: https://www.facebook.com/girlsrockri/
    Icon Image: "/uploads/facebook-icon.svg"
  Twitter:
    URL: https://twitter.com/girlsrockri
    Icon Image: "/uploads/twitter-icon.svg"
  Youtube:
    URL: https://www.youtube.com/channel/UCELKEtVnMcIL3ptJojOwKtQ
    Icon Image: "/uploads/youtube-icon.svg"
  Flickr:
    URL: https://www.flickr.com/photos/girlsrockri
    Icon Image: "/uploads/flickr-icon.svg"
